// Command dashboardd is the management dashboard's backend - see the
// rebranding/dashboard/client-native plan for the full architecture.
// Serves the SPA + a REST/JSON API for managing the node registry on one
// plain HTTP port (behind a single admin password - see internal/auth -
// forced setup on first run, session-cookie-gated after that; this port
// still isn't TLS-protected in transit, a known, documented limitation
// rather than a hidden one - see internal/auth's own doc comment), and
// one dedicated HTTPS listener per registered node (see dashboard/
// backend/internal/nodeproxy) requiring a TLS client certificate signed
// by that node's own CA - a browser already holding a valid client cert
// for that node gets prompted to select it the first time it connects
// to that node's own port.
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"embed"
	"encoding/json"
	"encoding/pem"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	pkcs12 "software.sslmate.com/src/go-pkcs12"

	janusv1alpha1 "github.com/swenske/Janus/gen/janus/v1alpha1"
	"github.com/swenske/Janus/internal/pki"

	"github.com/swenske/Janus/dashboard/backend/internal/auth"
	"github.com/swenske/Janus/dashboard/backend/internal/nodeproxy"
	"github.com/swenske/Janus/dashboard/backend/internal/store"
)

// staticFiles is dashboard/frontend's built React SPA - dashboard/
// backend/static, generated by `make dashboard-frontend-build`
// (dashboard/frontend's own `npm run build`, configured to output
// straight here - see vite.config.js). Committed to the repo the same
// way gen/janus/v1alpha1 is: never hand-edited, but committed
// anyway so a plain `go build ./...` never needs a Node.js toolchain
// just to compile - go:embed needs real files present at build time,
// not just at dashboard-image-build time.
//
//go:embed all:static
var staticFiles embed.FS

// portRangeStart/End: the pool of per-node listener ports - see the
// rebranding/dashboard plan's own architecture section for why a
// dynamic per-node port (not one shared port) is what makes native
// browser client-certificate selection work per node at all. Docker
// exposure needs either --network host or a pre-mapped
// "-p 9500-9599:9500-9599" - documented in dashboard/README.md once
// that lands (Dockerfile/publishing is a later tranche).
const (
	portRangeStart = 9500
	portRangeEnd   = 9599
)

func main() {
	addr := flag.String("addr", ":8080", "main HTTP address (node list, add/remove - never a credential)")
	dataDir := flag.String("data-dir", "/data", "persistent data directory (Docker volume) - node registry + this dashboard's own TLS identity")
	flag.Parse()

	st, err := store.Open(*dataDir)
	if err != nil {
		log.Fatalf("open store: %v", err)
	}

	authStore, err := auth.Open(*dataDir)
	if err != nil {
		log.Fatalf("open auth store: %v", err)
	}
	if authStore.SetupRequired() {
		log.Printf("no admin password set yet - the UI will force a one-time setup screen on first visit")
	}

	serverCert, err := loadOrCreateDashboardIdentity(*dataDir)
	if err != nil {
		log.Fatalf("dashboard TLS identity: %v", err)
	}

	app := &app{store: st, auth: authStore, serverCert: serverCert, listeners: map[string]*nodeproxy.Listener{}}
	for _, n := range st.List() {
		if err := app.startListener(n); err != nil {
			// A node whose listener fails to start (e.g. its port is
			// somehow already taken) stays registered but unreachable -
			// logged, not fatal, so one bad node doesn't take the whole
			// dashboard down on restart.
			log.Printf("node %s (%s): start listener: %v", n.ID, n.Name, err)
		}
	}

	spa, err := fs.Sub(staticFiles, "static")
	if err != nil {
		log.Fatalf("static assets: %v", err)
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/api/auth/status", app.handleAuthStatus)
	mux.HandleFunc("/api/auth/setup", app.handleAuthSetup)
	mux.HandleFunc("/api/auth/login", app.handleAuthLogin)
	mux.HandleFunc("/api/auth/logout", app.handleAuthLogout)
	mux.HandleFunc("/api/nodes", app.requireAuth(app.handleNodes))
	mux.HandleFunc("/api/nodes/", app.requireAuth(app.handleNode))
	mux.Handle("/", http.FileServerFS(spa))

	log.Printf("dashboardd listening on %s", *addr)
	log.Fatal(http.ListenAndServe(*addr, mux))
}

type app struct {
	store      *store.Store
	auth       *auth.Store
	serverCert tls.Certificate

	mu        sync.Mutex
	listeners map[string]*nodeproxy.Listener
}

func (a *app) startListener(n *store.Node) error {
	l, err := nodeproxy.Start(n, a.serverCert)
	if err != nil {
		return err
	}
	a.mu.Lock()
	a.listeners[n.ID] = l
	a.mu.Unlock()
	return nil
}

// addNodeRequest is the JSON form of "add a node": three raw PEM blocks
// pasted in directly. Superseded in the frontend by a .pfx upload (see
// parseAddNodeRequest below) - copying three separate PEM blocks by
// hand turned out to be real friction for one single one-time event,
// the same lesson cmd/janusd/main.go's own bootstrap print already
// learned (see its own comment on why the CA cert prints alongside the
// admin cert/key rather than being split across two recovery paths).
// Kept working, not just left for compatibility: hack/
// qemu-dashboard-test.sh drives this JSON path directly, and a script/
// CI caller with raw PEM files in hand (e.g. straight out of
// janusctl pki generate-client-config) has no reason to wrap them
// in a PKCS#12 file first just to satisfy the UI's preferred format.
type addNodeRequest struct {
	Name             string `json:"name"`
	Address          string `json:"address"`
	CACertPEM        string `json:"ca_cert_pem"`
	BootstrapCertPEM string `json:"bootstrap_cert_pem"`
	BootstrapKeyPEM  string `json:"bootstrap_key_pem"`
}

// parseAddNodeRequest reads name/address/CA-cert/bootstrap-cert/
// bootstrap-key from either a multipart/form-data upload (fields
// "name", "address", "pfx" file, "pfx_password" - the default the
// frontend now uses: a single .pfx file, no PEM text to paste at all)
// or the older addNodeRequest JSON body, dispatched on Content-Type.
// Both arrive at exactly the same three PEM blocks handleAddNode
// already knew what to do with - this function's only job is getting
// there from either shape.
func parseAddNodeRequest(r *http.Request) (name, address string, caPEM, certPEM, keyPEM []byte, err error) {
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
		// 1 MiB is generous for a .pfx holding one EC key + two small
		// certs (a few KB in practice) - just a sanity cap, not a real
		// constraint.
		if err := r.ParseMultipartForm(1 << 20); err != nil {
			return "", "", nil, nil, nil, fmt.Errorf("parse form: %w", err)
		}
		name = r.FormValue("name")
		address = r.FormValue("address")
		password := r.FormValue("pfx_password")

		file, _, ferr := r.FormFile("pfx")
		if ferr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("read pfx upload: %w", ferr)
		}
		defer file.Close()
		pfxData, rerr := io.ReadAll(file)
		if rerr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("read pfx upload: %w", rerr)
		}

		key, cert, caCerts, derr := pkcs12.DecodeChain(pfxData, password)
		if derr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("decode pfx (wrong password?): %w", derr)
		}
		if len(caCerts) == 0 {
			return "", "", nil, nil, nil, fmt.Errorf("pfx has no CA certificate bundled - it needs to include the node's ca.crt (e.g. openssl pkcs12 -export -certfile ca.crt ...)")
		}
		keyDER, merr := x509.MarshalPKCS8PrivateKey(key)
		if merr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("marshal private key from pfx: %w", merr)
		}
		certPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw})
		keyPEM = pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})
		caPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: caCerts[0].Raw})
		return name, address, caPEM, certPEM, keyPEM, nil
	}

	var req addNodeRequest
	if derr := json.NewDecoder(r.Body).Decode(&req); derr != nil {
		return "", "", nil, nil, nil, fmt.Errorf("decode request: %w", derr)
	}
	return req.Name, req.Address, []byte(req.CACertPEM), []byte(req.BootstrapCertPEM), []byte(req.BootstrapKeyPEM), nil
}

func (a *app) handleNodes(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		type nodeView struct {
			ID      string `json:"id"`
			Name    string `json:"name"`
			Address string `json:"address"`
			Port    int    `json:"port"`
		}
		var out []nodeView
		for _, n := range a.store.List() {
			out = append(out, nodeView{ID: n.ID, Name: n.Name, Address: n.Address, Port: n.Port})
		}
		writeJSON(w, http.StatusOK, out)

	case http.MethodPost:
		a.handleAddNode(w, r)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (a *app) handleAddNode(w http.ResponseWriter, r *http.Request) {
	name, address, caPEM, bootstrapCertPEM, bootstrapKeyPEM, err := parseAddNodeRequest(r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if name == "" || address == "" {
		http.Error(w, "name and address are required", http.StatusBadRequest)
		return
	}

	tlsConfig, err := pki.ClientTLSConfig(caPEM, bootstrapCertPEM, bootstrapKeyPEM)
	if err != nil {
		http.Error(w, fmt.Sprintf("build TLS config from provided credentials: %v", err), http.StatusBadRequest)
		return
	}
	conn, err := grpc.NewClient(address, grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)))
	if err != nil {
		http.Error(w, fmt.Sprintf("dial %s: %v", address, err), http.StatusBadGateway)
		return
	}
	defer conn.Close()

	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()
	cfg, err := janusv1alpha1.NewSystemServiceClient(conn).GenerateClientConfiguration(ctx, &janusv1alpha1.GenerateClientConfigurationRequest{
		Roles: []string{pki.RoleAdmin},
	})
	if err != nil {
		http.Error(w, fmt.Sprintf("GenerateClientConfiguration against %s: %v - the provided bootstrap credential couldn't reach or authenticate to that node", address, err), http.StatusBadGateway)
		return
	}
	// bootstrapCertPEM/bootstrapKeyPEM are never referenced again past
	// this point - only cfg's freshly-issued service credential is
	// persisted below.

	port, err := a.allocatePort()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInsufficientStorage)
		return
	}

	node := &store.Node{
		Name:           name,
		Address:        address,
		Port:           port,
		CACertPEM:      cfg.GetCa(),
		ServiceCertPEM: cfg.GetCrt(),
		ServiceKeyPEM:  cfg.GetKey(),
	}
	if err := a.store.Add(node); err != nil {
		http.Error(w, fmt.Sprintf("persist node: %v", err), http.StatusInternalServerError)
		return
	}
	if err := a.startListener(node); err != nil {
		http.Error(w, fmt.Sprintf("node registered but its listener failed to start: %v", err), http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusCreated, struct {
		ID   string `json:"id"`
		Port int    `json:"port"`
	}{ID: node.ID, Port: node.Port})
}

func (a *app) handleNode(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodDelete {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	id := r.URL.Path[len("/api/nodes/"):]
	if id == "" {
		http.Error(w, "missing node id", http.StatusBadRequest)
		return
	}

	a.mu.Lock()
	l, ok := a.listeners[id]
	delete(a.listeners, id)
	a.mu.Unlock()
	if ok {
		ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
		defer cancel()
		if err := l.Stop(ctx); err != nil {
			log.Printf("node %s: stop listener: %v", id, err)
		}
	}

	if err := a.store.Remove(id); err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// allocatePort returns the first port in [portRangeStart, portRangeEnd]
// not already used by a registered node - not concurrency-safe against
// two simultaneous add-node requests racing for the same port (fine for
// a first slice: this dashboard is a single operator's own tool, not a
// multi-tenant service).
func (a *app) allocatePort() (int, error) {
	used := a.store.UsedPorts()
	for p := portRangeStart; p <= portRangeEnd; p++ {
		if !used[p] {
			return p, nil
		}
	}
	return 0, fmt.Errorf("no free port in [%d, %d] - %d nodes already registered", portRangeStart, portRangeEnd, len(used))
}

// loadOrCreateDashboardIdentity gives every per-node listener a stable
// TLS server certificate across restarts (a fresh self-signed identity
// every restart would mean a new browser trust-warning every time,
// unrelated to whether anything actually changed). This certificate's
// own trust has nothing to do with authenticating *callers* - that's the
// per-node CA check in dashboard/backend/internal/nodeproxy - it only
// establishes the encrypted channel, so a self-signed one (reusing
// internal/pki's own CA+Issue machinery rather than writing new crypto
// code here) is enough for a first slice; a real certificate (or letting
// the operator supply their own) is a follow-up, not a blocker.
func loadOrCreateDashboardIdentity(dataDir string) (tls.Certificate, error) {
	certPath := dataDir + "/dashboard-identity.crt"
	keyPath := dataDir + "/dashboard-identity.key"

	if certPEM, err := os.ReadFile(certPath); err == nil {
		keyPEM, err := os.ReadFile(keyPath)
		if err == nil {
			return tls.X509KeyPair(certPEM, keyPEM)
		}
	}

	ca, err := pki.NewCA("dashboard")
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("generate dashboard identity: %w", err)
	}
	// App.jsx's openNode navigates to https://<window.location.hostname>:
	// <port>/ - whatever host the browser used to load the main SPA in
	// the first place (localhost most commonly, but not exclusively) -
	// so the SAN list needs to cover that, not just this process's own
	// view of itself. localhost/127.0.0.1/::1 are the guaranteed common
	// case; pki.LocalIPs() covers a real LAN address too, for a
	// --network host deployment or direct (non-Docker) local run - see
	// dashboard/README.md. A previous version issued this certificate
	// with zero SANs at all, which real modern TLS clients (browsers
	// included) reject outright regardless of CommonName.
	ips := append([]net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")}, pki.LocalIPs()...)
	certPEM, keyPEM, err := ca.Issue(pki.IssueOptions{
		CommonName:  "dashboard",
		DNSNames:    []string{"localhost"},
		IPAddresses: ips,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	})
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("issue dashboard server certificate: %w", err)
	}
	if err := os.WriteFile(certPath, certPEM, 0o600); err != nil {
		return tls.Certificate{}, fmt.Errorf("write %s: %w", certPath, err)
	}
	if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
		return tls.Certificate{}, fmt.Errorf("write %s: %w", keyPath, err)
	}
	return tls.X509KeyPair(certPEM, keyPEM)
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}
